import { QUALITY_GATES, type CharacterExpressionAsset, type MainlineCourse } from './domain.js'

const BASE_CAST_ROOT = '/generated-images/cast/base/middle/summer'
const STUDENT_CAST_IDS: Record<string, string> = {
  'student-chen': 'student-thinker',
  'student-k': 'student-joker',
  'student-k-physics': 'student-joker',
  'student-mei': 'student-steady',
  'student-zero': 'student-zero',
}

function normalizedExpression(expression: string): string {
  return ['neutral', 'happy', 'thinking', 'surprised'].includes(expression) ? expression : 'neutral'
}

function expressionAsset(prefix: string, expression: string): CharacterExpressionAsset {
  return {
    expression,
    src: `${BASE_CAST_ROOT}/${prefix}-${normalizedExpression(expression)}.png`,
    kind: 'half-body-cutout',
    transparentBackground: true,
  }
}

function studentAsset(fileName: string, expression: string): CharacterExpressionAsset {
  const characterId = STUDENT_CAST_IDS[fileName] ?? fileName
  return {
    expression,
    src: `${BASE_CAST_ROOT}/${characterId}-${normalizedExpression(expression)}.png`,
    kind: 'half-body-cutout',
    transparentBackground: true,
  }
}

export const GOLDEN_MAINLINE_COURSES: MainlineCourse[] = [
  {
    id: 'golden-primary-jingyesi',
    topic: '小学语文《静夜思》：看见月光，也看见乡愁',
    audience: '小学二年级，第一次完整学习古诗的学生',
    gradeBand: 'lower-primary',
    subject: 'chinese',
    sourceMaterial: [
      {
        kind: 'poem',
        title: '静夜思',
        excerpt: '床前明月光，疑是地上霜。举头望明月，低头思故乡。',
        citation: '李白《静夜思》',
      },
    ],
    goals: [
      {
        id: 'goal-read',
        statement: '学生能正确、完整、有节奏地读出《静夜思》。',
        successSignal: '学生能不漏字地朗读四句诗，并知道题目、作者和四句诗的位置关系。',
      },
      {
        id: 'goal-feeling',
        statement: '学生能说出诗中从“看见月光”到“想起故乡”的变化。',
        successSignal: '学生能用自己的话说出“举头”和“低头”带来的情感变化。',
      },
    ],
    boundary: '不扩展李白生平，不讲复杂格律，只完成原文标准展示、关键意象和乡愁理解。',
    selectedTeacher: 'teacher-xiaomei',
    teacherSubjectProfile: {
      teacherId: 'teacher-xiaomei',
      subject: 'chinese',
      teachingMode: 'text-close-reading',
      boardStyle: '中央原文 + 侧边微板书，低年级用短句和动作词。',
      techniquePreference: ['static-board', 'layered-reveal', 'local-zoom', 'step-replay'],
      voiceNotes: '温和、慢速，重读“举头”“低头”，每句后留短停顿。',
    },
    peerRoleProfile: {
      peerId: 'student-mei',
      allowedFunctions: ['questioner', 'peer-restate', 'emotion-buffer'],
      nonGoals: ['不抢答整首诗', '不替老师解释所有意象', '不制造无关笑点'],
    },
    castProfiles: [
      {
        id: 'teacher-xiaomei',
        role: 'teacher',
        displayName: '小梅老师',
        identity: '小学语文老师，擅长把动作和画面连起来教古诗。',
        gradeFit: ['lower-primary', 'upper-primary'],
        subjectFit: ['chinese'],
        visualIdentity: '米色外套、抱书、亲近但不幼稚的青年教师形象。',
        expressionSet: ['neutral', 'thinking', 'happy', 'surprised'],
        assetRefs: [
          expressionAsset('teacher-xiaomei', 'neutral'),
          expressionAsset('teacher-xiaomei', 'thinking'),
          expressionAsset('teacher-xiaomei', 'happy'),
          expressionAsset('teacher-xiaomei', 'surprised'),
        ],
      },
      {
        id: 'student-mei',
        role: 'student',
        displayName: '小米',
        identity: '低年级学生，负责说出初读疑问和复述。',
        gradeFit: ['lower-primary'],
        subjectFit: ['chinese'],
        visualIdentity: '圆润、好奇、低年级学生气质，出场只服务提问和复述。',
        expressionSet: ['curious', 'thinking'],
        assetRefs: [studentAsset('student-mei', 'curious')],
      },
    ],
    voiceProfiles: [
      {
        castId: 'teacher-xiaomei',
        voiceId: 'minimax:xiaomei-warm-stable',
        pace: 'slow',
        emotionRange: ['calm', 'encouraging', 'soft-emphasis'],
        stabilityRule: '同一课程全程使用同一女教师音色，只调整情绪强弱，不换声线。',
      },
      {
        castId: 'student-mei',
        voiceId: 'minimax:primary-girl-curious',
        pace: 'slow',
        emotionRange: ['curious', 'relieved'],
        stabilityRule: '只在学生提问和复述时出现，不承担老师讲解。',
      },
    ],
    gradeAdaptationProfile: {
      gradeBand: 'lower-primary',
      languageDensity: 'low',
      boardDensity: 'low',
      interactionDensity: 'medium',
      teacherPace: 'slow',
      roleMaturity: 'childlike',
    },
    teachingSkeleton: {
      id: 'skeleton-primary-poem-close-reading',
      knowledgeType: '古诗原文与情感动作',
      teachingType: '低年级古诗初学',
      arc: ['完整看诗', '看见月光', '动作变化', '复述乡愁'],
      requiredVisualForms: ['poem-display', 'local-zoom', 'step-replay'],
      requiredChecks: QUALITY_GATES,
      nonGoals: ['不做生平扩展', '不做整页人物装饰', '不把原文拆碎到看不完整'],
    },
    learningFragments: [
      {
        id: 'fragment-read-whole',
        goalId: 'goal-read',
        durationTargetSec: 70,
        sceneIds: ['jy-01-poem'],
        successSignal: '学生能看着标准诗面读完整首诗。',
      },
      {
        id: 'fragment-image-action',
        goalId: 'goal-feeling',
        durationTargetSec: 120,
        sceneIds: ['jy-02-moonlight', 'jy-03-action'],
        successSignal: '学生能说出月光像霜，动作从举头到低头。',
      },
      {
        id: 'fragment-restate',
        goalId: 'goal-feeling',
        durationTargetSec: 70,
        sceneIds: ['jy-04-recap'],
        successSignal: '学生能用一句话说出这首诗的情绪。',
      },
    ],
    scenes: [
      {
        id: 'jy-01-poem',
        sceneType: 'source-reading',
        visualLayout: 'poem-display / central-text-safe',
        contentSlots: {
          poemTitle: '静夜思',
          poemAuthor: '唐 · 李白',
          poemLines: '床前明月光，\n疑是地上霜。\n举头望明月，\n低头思故乡。',
        },
        visualFocus: '完整古诗原文',
        narrationAnchor: '完整古诗原文',
        syncStrategy: '先完整显示题目、作者和四句诗；老师只用旁白读，不让角色遮挡原文。',
        boardText: ['题目：静夜思', '作者：唐 · 李白', '先完整读，再看动作'],
        sceneTechnique: 'static-board',
        interactionContract: '学生只跟读，不点击；读完后进入逐句观察。',
        fallbackPresentation: '如果立绘或动画加载失败，保留中央诗面和旁白。',
        characterLayer: {
          layout: 'no-character',
          positionRule: '原文完整展示时角色完全退场。',
          exitRule: '读完四句后允许老师以角落头像回到下一页。',
        },
        dialogueLayout: 'no-character',
        peerFunction: 'none',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'teacher-xiaomei',
          emotion: 'calm',
          pace: 'slow',
          pauseRule: '每句诗后停 700ms，题目和作者后停 900ms。',
        },
        gradeTone: '低年级短句、慢速、少概念词。',
        teacherScript: '先看完整古诗原文。题目是《静夜思》，作者是唐代诗人李白。我们先不急着解释，眼睛跟着四句诗走一遍：床前明月光，疑是地上霜。举头望明月，低头思故乡。读完以后，我们再看诗里的人先看见了什么，又做了什么动作。',
        studentAction: '跟读四句诗，确认题目、作者和每一句的位置。',
        evidenceOnScreen: ['静夜思', '唐 · 李白', '四句诗原文'],
      },
      {
        id: 'jy-02-moonlight',
        sceneType: 'visual-observation',
        visualLayout: 'teacher-left / content-right / local-zoom',
        contentSlots: {
          mainImage: '月光落在床前，地面像有一层白霜。',
          zoomTarget: '明月光 → 地上霜',
        },
        visualFocus: '月光像霜',
        narrationAnchor: '月光像霜',
        syncStrategy: '老师在左侧半身讲解，右侧主画面保持不动，只局部放大“月光像霜”。',
        boardText: ['明月光：看到的景', '疑是霜：像什么', '先看见，再产生联想'],
        sceneTechnique: 'local-zoom',
        interactionContract: '学生观察放大窗，说出“月光”和“霜”的相似点。',
        fallbackPresentation: '放大失败时用左右两栏：月光 / 霜，并保留关键词。',
        characterLayer: {
          castId: 'teacher-xiaomei',
          expression: 'thinking',
          layout: 'teacher-left-content-right',
          positionRule: '老师半身在左下安全区，肩部不超过画面 35%，不覆盖右侧月光区。',
          exitRule: '进入完整诗面或原文密集页时退场。',
        },
        dialogueLayout: 'teacher-left-content-right',
        peerFunction: 'none',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'teacher-xiaomei',
          emotion: 'soft-emphasis',
          pace: 'slow',
          pauseRule: '说到“疑是”时停顿，让学生观察像不像。',
        },
        gradeTone: '用“像不像”“先看到什么”这样的低年级提问。',
        teacherScript: '这里的讲解锚点是月光像霜。李白不是先说自己很想家，而是先让我们看见床前的月光。月光很亮，铺在地上，白白的一片，所以他会疑是地上霜。这个“疑”很重要，意思是他一开始还不确定，只是觉得眼前的白光很像霜。',
        studentAction: '看右侧局部放大，说出月光和霜都给人白、冷、静的感觉。',
        evidenceOnScreen: ['床前明月光', '疑是地上霜', '月光局部放大'],
      },
      {
        id: 'jy-03-action',
        sceneType: 'contrast',
        visualLayout: 'student-right / content-left / action-contrast',
        contentSlots: {
          leftAction: '举头望明月',
          rightAction: '低头思故乡',
        },
        visualFocus: '举头和低头',
        narrationAnchor: '举头和低头',
        syncStrategy: '左侧用两个动作对照，学生立绘在右侧提出问题，对白框放在左侧动作区下方空白处。',
        boardText: ['举头：看月亮', '低头：想故乡', '动作带出情绪变化'],
        sceneTechnique: 'comparison-slider',
        interactionContract: '学生点击“举头 / 低头”切换当前动作，观察情绪从看见到想念。',
        fallbackPresentation: '如果滑块不可用，左右并排显示两个动作和对应诗句。',
        characterLayer: {
          castId: 'student-mei',
          expression: 'curious',
          layout: 'student-right-content-left',
          positionRule: '学生半身在右下安全区，只占画面右侧 24%，不遮挡动作对照。',
          exitRule: '学生提问后退成角落头像。',
        },
        dialogueLayout: 'student-right-content-left',
        peerFunction: 'questioner',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'student-mei',
          emotion: 'curious',
          pace: 'slow',
          pauseRule: '问题后停 900ms，给学生观察动作对照。',
        },
        gradeTone: '同学提问短而真实，不替老师总结。',
        teacherScript: '这一页看举头和低头。小米会问：为什么先举头，后来又低头？我们把两个动作放在一起看。举头，是眼睛看向明月；低头，是心里想起故乡。诗人没有直接说“我想家了”，而是用两个动作，让我们看见情绪慢慢转过来。',
        studentAction: '学生点击或观察两个动作，说出“看月亮”和“想故乡”的不同。',
        evidenceOnScreen: ['举头望明月', '低头思故乡', '动作对照'],
      },
      {
        id: 'jy-04-recap',
        sceneType: 'recap',
        visualLayout: 'corner-avatar / step-replay',
        contentSlots: {
          steps: '看见月光 → 觉得像霜 → 举头望月 → 低头思乡',
        },
        visualFocus: '从景到情的四步',
        narrationAnchor: '从景到情',
        syncStrategy: '老师退为角落头像，中央步骤条逐步回放，板书保持在下方。',
        boardText: ['景：月光', '联想：霜', '动作：举头 / 低头', '情：思故乡'],
        sceneTechnique: 'step-replay',
        interactionContract: '学生按顺序复述四步，系统只高亮当前步骤。',
        fallbackPresentation: '静态四步流程图，保留当前步骤高亮。',
        characterLayer: {
          castId: 'teacher-xiaomei',
          expression: 'happy',
          layout: 'corner-avatar',
          positionRule: '老师只保留左下角头像，不再使用大半身。',
          exitRule: '复述完成后隐藏角色。',
        },
        dialogueLayout: 'corner-avatar',
        peerFunction: 'peer-restate',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'teacher-xiaomei',
          emotion: 'encouraging',
          pace: 'slow',
          pauseRule: '每一步后留出跟读停顿。',
        },
        gradeTone: '用短句复述，先说画面，再说心情。',
        teacherScript: '最后把这节课收回来：从景到情。先看见月光，再觉得像霜；先举头望明月，再低头思故乡。你会发现，诗里没有长篇解释，只有一个安静的画面和两个动作。现在请你按这四步复述一遍，说明李白是怎么从看见月光想到故乡的。',
        studentAction: '按四步复述诗意，不要求背诵背景知识。',
        evidenceOnScreen: ['月光', '霜', '举头', '低头', '思故乡'],
      },
    ],
    beats: [
      { id: 'jy-b01', sceneId: 'jy-01-poem', action: 'reveal', targetId: 'poemTitle', durationMs: 700 },
      { id: 'jy-b02', sceneId: 'jy-01-poem', action: 'speak', script: '完整朗读四句诗', durationMs: 12000 },
      { id: 'jy-b03', sceneId: 'jy-02-moonlight', action: 'point', targetId: 'moonlight', durationMs: 1800 },
      { id: 'jy-b04', sceneId: 'jy-02-moonlight', action: 'reveal', targetId: 'zoomTarget', durationMs: 1800 },
      { id: 'jy-b05', sceneId: 'jy-03-action', action: 'ask', targetId: 'student-question', durationMs: 2600 },
      { id: 'jy-b06', sceneId: 'jy-03-action', action: 'reveal', targetId: 'action-contrast', durationMs: 2200 },
      { id: 'jy-b07', sceneId: 'jy-04-recap', action: 'reveal', targetId: 'steps', durationMs: 3000 },
      { id: 'jy-b08', sceneId: 'jy-04-recap', action: 'wait', targetId: 'student-restate', durationMs: 2500 },
    ],
    qualityStatus: 'passed',
  },
  {
    id: 'golden-middle-tianjingsha',
    topic: '初中语文《天净沙·秋思》：用意象推进孤独感',
    audience: '初中一年级，已接触古诗词但需要建立意象分析方法的学生',
    gradeBand: 'middle-school',
    subject: 'chinese',
    sourceMaterial: [
      {
        kind: 'poem',
        title: '天净沙·秋思',
        excerpt: '枯藤老树昏鸦，小桥流水人家，古道西风瘦马。夕阳西下，断肠人在天涯。',
        citation: '马致远《天净沙·秋思》',
      },
    ],
    goals: [
      {
        id: 'goal-imagery',
        statement: '学生能区分并解释曲中的核心意象组。',
        successSignal: '学生能把前三句分成衰败、温暖、远行三组，并说明它们如何互相衬托。',
      },
      {
        id: 'goal-emotion-path',
        statement: '学生能说明“断肠人在天涯”不是孤立结论，而是前面意象推动出的情绪落点。',
        successSignal: '学生能沿着意象路径说出孤独感如何逐步加重。',
      },
    ],
    boundary: '不扩展元曲格律和文学史，只解决意象关系、画面推进和情感落点。',
    selectedTeacher: 'teacher-professor',
    teacherSubjectProfile: {
      teacherId: 'teacher-professor',
      subject: 'chinese',
      teachingMode: 'text-close-reading',
      boardStyle: '三组意象 + 情绪路径，初中可使用“衬托”“落点”等术语。',
      techniquePreference: ['static-board', 'path-tracing', 'comparison-slider', 'step-replay'],
      voiceNotes: '沉稳、清晰，意象分析处放慢，结论处降低音量。',
    },
    peerRoleProfile: {
      peerId: 'student-chen',
      allowedFunctions: ['questioner', 'misconception', 'comparison'],
      nonGoals: ['不把“小桥流水人家”简单理解成快乐段落', '不讨论作者八卦'],
    },
    castProfiles: [
      {
        id: 'teacher-professor',
        role: 'teacher',
        displayName: '陈教授',
        identity: '初中文学讲解老师，擅长把画面组织成分析路径。',
        gradeFit: ['middle-school', 'high-school'],
        subjectFit: ['chinese', 'history'],
        visualIdentity: '沉稳、成熟、偏人文学者气质，适合中学文本细读。',
        expressionSet: ['neutral', 'thinking', 'happy', 'surprised'],
        assetRefs: [
          expressionAsset('teacher-professor', 'neutral'),
          expressionAsset('teacher-professor', 'thinking'),
          expressionAsset('teacher-professor', 'happy'),
          expressionAsset('teacher-professor', 'surprised'),
        ],
      },
      {
        id: 'student-chen',
        role: 'student',
        displayName: '陈同学',
        identity: '初中学生，负责提出容易误解的文本问题。',
        gradeFit: ['middle-school'],
        subjectFit: ['chinese'],
        visualIdentity: '比小学角色更克制，提问偏分析，不负责卖萌。',
        expressionSet: ['questioning', 'thinking'],
        assetRefs: [studentAsset('student-chen', 'questioning')],
      },
    ],
    voiceProfiles: [
      {
        castId: 'teacher-professor',
        voiceId: 'zhipu:professor-chen-stable',
        pace: 'medium',
        emotionRange: ['calm', 'analytical', 'low-emphasis'],
        stabilityRule: '陈教授同课全程使用同一沉稳男声，不能在讲解段落中变声。',
      },
      {
        castId: 'student-chen',
        voiceId: 'zhipu:middle-school-boy-questioning',
        pace: 'medium',
        emotionRange: ['questioning', 'thinking'],
        stabilityRule: '只承担问题和误区暴露，不替老师做长讲解。',
      },
    ],
    gradeAdaptationProfile: {
      gradeBand: 'middle-school',
      languageDensity: 'medium',
      boardDensity: 'medium',
      interactionDensity: 'medium',
      teacherPace: 'medium',
      roleMaturity: 'balanced',
    },
    teachingSkeleton: {
      id: 'skeleton-middle-poem-imagery-path',
      knowledgeType: '意象组织与情感落点',
      teachingType: '初中文本细读',
      arc: ['完整读曲', '分组观察', '误区对照', '路径复盘'],
      requiredVisualForms: ['poem-display', 'triptych-imagery', 'contrast', 'path-replay'],
      requiredChecks: QUALITY_GATES,
      nonGoals: ['不做景物堆砌图鉴', '不做固定气泡标注', '不把角色长期压在画面上'],
    },
    learningFragments: [
      {
        id: 'fragment-source-standard',
        goalId: 'goal-imagery',
        durationTargetSec: 80,
        sceneIds: ['tj-01-source'],
        successSignal: '学生能看到完整曲面，不被角色和注释遮挡。',
      },
      {
        id: 'fragment-imagery-path',
        goalId: 'goal-emotion-path',
        durationTargetSec: 130,
        sceneIds: ['tj-02-triptych', 'tj-03-contrast'],
        successSignal: '学生能说明“小桥流水人家”如何反衬旅人孤独。',
      },
      {
        id: 'fragment-emotion-replay',
        goalId: 'goal-emotion-path',
        durationTargetSec: 70,
        sceneIds: ['tj-04-path'],
        successSignal: '学生能沿路径复述孤独感的推进。',
      },
    ],
    scenes: [
      {
        id: 'tj-01-source',
        sceneType: 'source-reading',
        visualLayout: 'poem-display / central-text-safe',
        contentSlots: {
          poemTitle: '天净沙·秋思',
          poemAuthor: '元 · 马致远',
          poemLines: '枯藤老树昏鸦，\n小桥流水人家，\n古道西风瘦马。\n夕阳西下，\n断肠人在天涯。',
        },
        visualFocus: '完整曲文',
        narrationAnchor: '完整曲文',
        syncStrategy: '完整曲文居中，角色退场，只保留朗读和轻微行间高亮。',
        boardText: ['先完整看曲文', '再看意象如何排列', '最后回到情绪落点'],
        sceneTechnique: 'static-board',
        interactionContract: '学生不操作，先完整听读。',
        fallbackPresentation: '保留中央曲文和逐行高亮，不依赖角色。',
        characterLayer: {
          layout: 'no-character',
          positionRule: '曲文完整展示时无角色。',
          exitRule: '进入分析页后老师从左侧入场。',
        },
        dialogueLayout: 'no-character',
        peerFunction: 'none',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'teacher-professor',
          emotion: 'calm',
          pace: 'medium',
          pauseRule: '前三句之间短停，最后两句前停 900ms。',
        },
        gradeTone: '初中语文，可使用意象、衬托、落点，但每个术语都绑定画面。',
        teacherScript: '先看完整曲文。《天净沙·秋思》不是把景物随便排在一起，而是让画面一步步把人推向最后一句。我们先完整读：枯藤老树昏鸦，小桥流水人家，古道西风瘦马。夕阳西下，断肠人在天涯。接下来重点看这些意象怎样排列。',
        studentAction: '完整听读，标出自己第一眼最明显的画面。',
        evidenceOnScreen: ['完整曲文', '题目', '作者'],
      },
      {
        id: 'tj-02-triptych',
        sceneType: 'visual-observation',
        visualLayout: 'three-panel-imagery / narration-only',
        contentSlots: {
          panelA: '枯藤、老树、昏鸦：衰败和傍晚感',
          panelB: '小桥、流水、人家：温暖和归属感',
          panelC: '古道、西风、瘦马：远行和疲惫感',
        },
        visualFocus: '三组意象',
        narrationAnchor: '三组意象',
        syncStrategy: '三栏固定，不再用浮动标注圈住画面；按讲解顺序让三组标题和关键词显现。',
        boardText: ['衰败：枯藤 / 老树 / 昏鸦', '温暖：小桥 / 流水 / 人家', '远行：古道 / 西风 / 瘦马'],
        sceneTechnique: 'path-tracing',
        interactionContract: '学生按路径从左到右读三组意象，判断每组带来的感受。',
        fallbackPresentation: '三栏静态画面加 1-2-3 路径节点。',
        characterLayer: {
          layout: 'narration-only',
          positionRule: '三组意象同时需要完整展示，角色退场，只保留旁白字幕。',
          exitRule: '学生误区出现时切换为角落头像。',
        },
        dialogueLayout: 'narration-only',
        peerFunction: 'none',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'teacher-professor',
          emotion: 'analytical',
          pace: 'medium',
          pauseRule: '每组意象讲完停 600ms，路径移动再讲下一组。',
        },
        gradeTone: '用“意象组”和“感受方向”组织分析，避免只翻译词语。',
        teacherScript: '这一页的锚点是三组意象。第一组，枯藤、老树、昏鸦，颜色和生命感都往下沉。第二组，小桥、流水、人家，看上去温暖，有生活气息。第三组，古道、西风、瘦马，又把我们带回远行和疲惫。画面不是简单并列，而是在对比中把旅人的孤独推出来。',
        studentAction: '按三栏路径说出每组意象给人的感受。',
        evidenceOnScreen: ['枯藤老树昏鸦', '小桥流水人家', '古道西风瘦马'],
      },
      {
        id: 'tj-03-contrast',
        sceneType: 'contrast',
        visualLayout: 'corner-avatar / contrast-question',
        contentSlots: {
          misconception: '小桥流水人家是不是突然变轻松？',
          correction: '它越温暖，越衬出旅人不在家。',
        },
        visualFocus: '小桥流水人家的反衬作用',
        narrationAnchor: '反衬作用',
        syncStrategy: '角色只用角落头像，中央保留左右对照：误解 / 修正。',
        boardText: ['误解：这里变轻松', '修正：温暖反衬孤独', '关键：旅人不在“人家”里'],
        sceneTechnique: 'comparison-slider',
        interactionContract: '学生在误解和修正之间切换，判断哪一种能连到最后一句。',
        fallbackPresentation: '左右并排显示误解和修正，不使用动态滑块。',
        characterLayer: {
          castId: 'student-chen',
          expression: 'questioning',
          layout: 'corner-avatar',
          positionRule: '学生只以右下角头像出现，不遮挡中央对照。',
          exitRule: '误区澄清后头像淡出。',
        },
        dialogueLayout: 'corner-avatar',
        peerFunction: 'misconception',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'student-chen',
          emotion: 'questioning',
          pace: 'medium',
          pauseRule: '提问后停 700ms，再由老师接续。',
        },
        gradeTone: '初中学生的问题应有分析价值，不做表层热闹。',
        teacherScript: '这里处理一个常见误解：反衬作用。陈同学会问，小桥流水人家是不是让画面突然变轻松？如果只看这一句，好像是温暖的。但正因为有人家、有流水、有可以回去的生活，旅人却仍在路上，孤独感才更强。这个温暖不是打断秋思，而是在反衬秋思。',
        studentAction: '判断“小桥流水人家”是转轻松，还是反衬旅人孤独。',
        evidenceOnScreen: ['小桥流水人家', '断肠人在天涯', '误解 / 修正对照'],
      },
      {
        id: 'tj-04-path',
        sceneType: 'recap',
        visualLayout: 'path-replay / corner-avatar',
        contentSlots: {
          path: '衰败景 → 温暖家 → 远行人 → 夕阳下 → 天涯孤独',
        },
        visualFocus: '孤独感推进路径',
        narrationAnchor: '孤独感推进路径',
        syncStrategy: '老师退为角落头像，中央路径回放；当前路径节点高亮，其余节点不移动。',
        boardText: ['不是景物清单', '是情绪推进', '最后落到“天涯”'],
        sceneTechnique: 'step-replay',
        interactionContract: '学生按路径复述，系统高亮当前节点。',
        fallbackPresentation: '静态路径图加当前节点高亮。',
        characterLayer: {
          castId: 'teacher-professor',
          expression: 'thinking',
          layout: 'corner-avatar',
          positionRule: '老师只保留左下角头像，中央路径至少保留 80% 宽度。',
          exitRule: '路径完整回放后隐藏角色。',
        },
        dialogueLayout: 'corner-avatar',
        peerFunction: 'peer-restate',
        subjectTeachingMode: 'text-close-reading',
        voiceCue: {
          castId: 'teacher-professor',
          emotion: 'low-emphasis',
          pace: 'medium',
          pauseRule: '最后一句前明显降速并停顿。',
        },
        gradeTone: '允许使用“推进”“落点”，但每个词都要回到屏幕证据。',
        teacherScript: '最后复盘孤独感推进路径。它不是景物清单：先是衰败的景，再出现温暖的人家，接着是远行的古道、西风、瘦马，夕阳把时间压低，最后才落到“断肠人在天涯”。所以最后一句不是突然抒情，而是前面每一组意象把它推到了那里。',
        studentAction: '沿路径复述：每一组意象怎样把孤独感加重。',
        evidenceOnScreen: ['衰败景', '温暖家', '远行人', '夕阳', '天涯'],
      },
    ],
    beats: [
      { id: 'tj-b01', sceneId: 'tj-01-source', action: 'reveal', targetId: 'poemTitle', durationMs: 700 },
      { id: 'tj-b02', sceneId: 'tj-01-source', action: 'speak', script: '完整读曲', durationMs: 14000 },
      { id: 'tj-b03', sceneId: 'tj-02-triptych', action: 'reveal', targetId: 'panelA', durationMs: 1600 },
      { id: 'tj-b04', sceneId: 'tj-02-triptych', action: 'reveal', targetId: 'panelB', durationMs: 1600 },
      { id: 'tj-b05', sceneId: 'tj-02-triptych', action: 'reveal', targetId: 'panelC', durationMs: 1600 },
      { id: 'tj-b06', sceneId: 'tj-03-contrast', action: 'ask', targetId: 'misconception', durationMs: 2200 },
      { id: 'tj-b07', sceneId: 'tj-03-contrast', action: 'reveal', targetId: 'correction', durationMs: 2200 },
      { id: 'tj-b08', sceneId: 'tj-04-path', action: 'reveal', targetId: 'path', durationMs: 3200 },
      { id: 'tj-b09', sceneId: 'tj-04-path', action: 'wait', targetId: 'student-restate', durationMs: 2500 },
    ],
    qualityStatus: 'passed',
  },
  {
    id: 'golden-middle-refraction',
    topic: '初中物理：光从空气进入水时为什么会偏折',
    audience: '初中物理入门学生，第一次学习折射现象',
    gradeBand: 'middle-school',
    subject: 'physics',
    sourceMaterial: [
      {
        kind: 'experiment-data',
        title: '光的折射观察',
        excerpt: '一束光从空气斜射入水中，传播方向在分界面处发生改变。',
        citation: '初中物理光学入门实验',
      },
    ],
    goals: [
      {
        id: 'goal-observe-refraction',
        statement: '学生能观察并说出光在空气和水的分界面处发生偏折。',
        successSignal: '学生能在示意图上指出入射光线、折射光线和法线。',
      },
      {
        id: 'goal-variable',
        statement: '学生能初步判断入射角变化会影响折射方向。',
        successSignal: '学生能拖动入射角并描述折射光线如何变化。',
      },
    ],
    boundary: '不讲斯涅尔定律和复杂计算，只建立观察、术语和变量关系。',
    selectedTeacher: 'teacher-young',
    teacherSubjectProfile: {
      teacherId: 'teacher-young',
      subject: 'physics',
      teachingMode: 'experiment-observation',
      boardStyle: '实验图 + 术语标签 + 变量观察。',
      techniquePreference: ['simulation', 'dynamic-chart', 'draggable-model', 'step-replay'],
      voiceNotes: '清楚、克制，强调观察顺序，不用夸张语气。',
    },
    peerRoleProfile: {
      peerId: 'student-k-physics',
      allowedFunctions: ['attempt-answer', 'misconception', 'questioner'],
      nonGoals: ['不提前讲公式', '不把折射解释成反射'],
    },
    castProfiles: [
      {
        id: 'teacher-young',
        role: 'teacher',
        displayName: '杨老师',
        identity: '初中理科老师，擅长用实验观察引出概念。',
        gradeFit: ['middle-school'],
        subjectFit: ['physics', 'science'],
        visualIdentity: '理科教师形象，表情克制，重点服务实验观察。',
        expressionSet: ['neutral', 'thinking', 'happy', 'surprised'],
        assetRefs: [
          expressionAsset('teacher-young', 'neutral'),
          expressionAsset('teacher-young', 'thinking'),
          expressionAsset('teacher-young', 'happy'),
          expressionAsset('teacher-young', 'surprised'),
        ],
      },
      {
        id: 'student-k-physics',
        role: 'student',
        displayName: 'K 同学',
        identity: '初中理科学生，负责尝试解释和暴露误区。',
        gradeFit: ['middle-school'],
        subjectFit: ['physics', 'science'],
        visualIdentity: '理科学生气质，出场时拿观察记录板。',
        expressionSet: ['attempt', 'confused'],
        assetRefs: [studentAsset('student-k-physics', 'attempt')],
      },
    ],
    voiceProfiles: [
      {
        castId: 'teacher-young',
        voiceId: 'zhipu:science-teacher-young-stable',
        pace: 'medium',
        emotionRange: ['calm', 'clear-emphasis', 'encouraging'],
        stabilityRule: '同一理科老师使用稳定中性音色，实验步骤不换角色声线。',
      },
      {
        castId: 'student-k-physics',
        voiceId: 'zhipu:middle-school-student-k',
        pace: 'medium',
        emotionRange: ['attempt', 'confused'],
        stabilityRule: '只用于尝试作答和误区暴露。',
      },
    ],
    gradeAdaptationProfile: {
      gradeBand: 'middle-school',
      languageDensity: 'medium',
      boardDensity: 'medium',
      interactionDensity: 'high',
      teacherPace: 'medium',
      roleMaturity: 'balanced',
    },
    teachingSkeleton: {
      id: 'skeleton-refraction-observation',
      knowledgeType: '物理现象观察与变量关系',
      teachingType: '实验观察引出概念',
      arc: ['观察现象', '标出术语', '改变变量', '回放结论'],
      requiredVisualForms: ['simulation', 'labelled-diagram', 'draggable-model', 'step-replay'],
      requiredChecks: QUALITY_GATES,
      nonGoals: ['不做公式推导', '不做复杂三维动画', '不让角色遮挡实验图'],
    },
    learningFragments: [
      {
        id: 'fragment-observe',
        goalId: 'goal-observe-refraction',
        durationTargetSec: 100,
        sceneIds: ['rf-01-observe', 'rf-02-labels'],
        successSignal: '学生能指出光在分界面处改变方向。',
      },
      {
        id: 'fragment-variable',
        goalId: 'goal-variable',
        durationTargetSec: 110,
        sceneIds: ['rf-03-drag', 'rf-04-recap'],
        successSignal: '学生能拖动入射角并描述变化方向。',
      },
    ],
    scenes: [
      {
        id: 'rf-01-observe',
        sceneType: 'visual-observation',
        visualLayout: 'teacher-left / simulation-right',
        contentSlots: {
          experiment: '空气、水、分界面、斜射光线',
        },
        visualFocus: '光在分界面处偏折',
        narrationAnchor: '光在分界面处偏折',
        syncStrategy: '右侧模拟图固定，老师在左侧讲观察顺序，光线路径逐步显现。',
        boardText: ['先看分界面', '再看光线方向', '方向改变 = 偏折'],
        sceneTechnique: 'simulation',
        interactionContract: '先不拖动，只观察光线路径在分界面处的改变。',
        fallbackPresentation: '用三帧静态图显示入射、到达分界面、进入水中。',
        characterLayer: {
          castId: 'teacher-young',
          expression: 'neutral',
          layout: 'teacher-left-content-right',
          positionRule: '老师在左侧安全区，右侧实验图占 65% 以上。',
          exitRule: '进入术语密集页时退为角落头像。',
        },
        dialogueLayout: 'teacher-left-content-right',
        peerFunction: 'none',
        subjectTeachingMode: 'experiment-observation',
        voiceCue: {
          castId: 'teacher-young',
          emotion: 'clear-emphasis',
          pace: 'medium',
          pauseRule: '光线到达分界面时停顿 500ms。',
        },
        gradeTone: '初中理科，先观察再给概念，避免公式化。',
        teacherScript: '这节课先观察光在分界面处偏折。屏幕右侧有空气和水，中间是一条分界面。我们让一束光斜着从空气进入水，先看它到达分界面之前的方向，再看进入水之后的方向。方向在这里改变了，这个现象就叫折射。',
        studentAction: '观察光线在分界面前后方向是否一致。',
        evidenceOnScreen: ['空气', '水', '分界面', '入射光线', '折射光线'],
      },
      {
        id: 'rf-02-labels',
        sceneType: 'concept-build',
        visualLayout: 'corner-avatar / labelled-diagram',
        contentSlots: {
          labels: '入射光线、折射光线、法线、入射角、折射角',
        },
        visualFocus: '入射光线、折射光线和法线',
        narrationAnchor: '法线',
        syncStrategy: '角色退为角落头像，中央实验图不移动，只逐个显现术语标签。',
        boardText: ['入射光线：进来的一段', '折射光线：进入水后的一段', '法线：垂直分界面的参考线'],
        sceneTechnique: 'layered-reveal',
        interactionContract: '学生按顺序点亮三个标签，确认每个词对应的线。',
        fallbackPresentation: '静态标注图和编号术语表。',
        characterLayer: {
          castId: 'teacher-young',
          expression: 'thinking',
          layout: 'corner-avatar',
          positionRule: '老师头像在左下角，标签区完整可见。',
          exitRule: '学生操作时保持头像，不使用半身。',
        },
        dialogueLayout: 'corner-avatar',
        peerFunction: 'none',
        subjectTeachingMode: 'experiment-observation',
        voiceCue: {
          castId: 'teacher-young',
          emotion: 'calm',
          pace: 'medium',
          pauseRule: '每个标签显现后停 400ms。',
        },
        gradeTone: '术语一次只给一个，马上绑定图上的线。',
        teacherScript: '现在补一个关键锚点：法线。法线不是一条真实光线，而是我们为了比较角度画出的参考线。先看入射光线，就是进来的一段；再看折射光线，就是进入水之后的一段；最后看法线，它垂直于分界面，帮助我们描述光线偏折了多少。',
        studentAction: '按顺序指出入射光线、折射光线和法线。',
        evidenceOnScreen: ['入射光线', '折射光线', '法线'],
      },
      {
        id: 'rf-03-drag',
        sceneType: 'practice',
        visualLayout: 'narration-only / draggable-model',
        contentSlots: {
          draggable: '拖动入射光线角度，观察折射光线变化。',
        },
        visualFocus: '入射角改变后的折射光线',
        narrationAnchor: '入射角改变',
        syncStrategy: '角色退场，中央保留可拖模型和反馈文字；拖动时只更新光线，不改变坐标和标签位置。',
        boardText: ['改变入射角', '观察折射光线', '描述变化，不背公式'],
        sceneTechnique: 'draggable-model',
        interactionContract: '学生拖动入射光线端点；系统即时更新折射光线，并提示“方向改变更明显 / 更接近法线”。',
        fallbackPresentation: '显示小角度、中角度、大角度三种状态帧。',
        characterLayer: {
          layout: 'narration-only',
          positionRule: '练习操作时无半身角色，避免遮挡可拖对象。',
          exitRule: '完成拖动后学生头像进入复述页。',
        },
        dialogueLayout: 'narration-only',
        peerFunction: 'attempt-answer',
        subjectTeachingMode: 'experiment-observation',
        voiceCue: {
          castId: 'teacher-young',
          emotion: 'clear-emphasis',
          pace: 'medium',
          pauseRule: '拖动后停 500ms，让学生先看变化。',
        },
        gradeTone: '强调观察和描述，不急着计算。',
        teacherScript: '现在观察入射角改变。请拖动入射光线的端点，让它更斜或更接近法线。注意看，分界面不动，法线不动，改变的是入射光线和折射光线的方向。我们现在只描述现象：入射角改变后，折射光线也会跟着改变。',
        studentAction: '拖动入射光线端点，说出折射光线如何变化。',
        evidenceOnScreen: ['可拖入射光线', '折射光线', '法线', '角度反馈'],
      },
      {
        id: 'rf-04-recap',
        sceneType: 'recap',
        visualLayout: 'student-right / step-replay',
        contentSlots: {
          steps: '看分界面 → 看方向改变 → 标术语 → 改变量观察',
        },
        visualFocus: '折射学习路径',
        narrationAnchor: '折射学习路径',
        syncStrategy: '学生在右侧尝试复述，左侧步骤回放保持固定。',
        boardText: ['现象：方向改变', '术语：入射 / 折射 / 法线', '变量：入射角改变'],
        sceneTechnique: 'step-replay',
        interactionContract: '学生按四步复述，系统只高亮当前步骤。',
        fallbackPresentation: '静态四步列表和结论。',
        characterLayer: {
          castId: 'student-k-physics',
          expression: 'attempt',
          layout: 'student-right-content-left',
          positionRule: '学生半身在右侧安全区，左侧步骤区完整可见。',
          exitRule: '复述完成后退为角落头像。',
        },
        dialogueLayout: 'student-right-content-left',
        peerFunction: 'attempt-answer',
        subjectTeachingMode: 'experiment-observation',
        voiceCue: {
          castId: 'student-k-physics',
          emotion: 'attempt',
          pace: 'medium',
          pauseRule: '每步复述后停 500ms。',
        },
        gradeTone: '学生复述用自然语言，不背定义。',
        teacherScript: '最后回到折射学习路径。第一步，看分界面；第二步，看光线方向是不是改变；第三步，标出入射光线、折射光线和法线；第四步，改变入射角观察变化。K 同学可以这样说：光斜着从空气进入水，在分界面处方向改变，这就是折射。',
        studentAction: '按四步复述折射现象和关键术语。',
        evidenceOnScreen: ['分界面', '方向改变', '法线', '入射角改变'],
      },
    ],
    beats: [
      { id: 'rf-b01', sceneId: 'rf-01-observe', action: 'reveal', targetId: 'incident-ray', durationMs: 1000 },
      { id: 'rf-b02', sceneId: 'rf-01-observe', action: 'reveal', targetId: 'refracted-ray', durationMs: 1200 },
      { id: 'rf-b03', sceneId: 'rf-02-labels', action: 'reveal', targetId: 'normal-line', durationMs: 900 },
      { id: 'rf-b04', sceneId: 'rf-02-labels', action: 'point', targetId: 'labels', durationMs: 1800 },
      { id: 'rf-b05', sceneId: 'rf-03-drag', action: 'ask', targetId: 'drag-handle', durationMs: 1800 },
      { id: 'rf-b06', sceneId: 'rf-03-drag', action: 'react', targetId: 'angle-feedback', durationMs: 1800 },
      { id: 'rf-b07', sceneId: 'rf-04-recap', action: 'reveal', targetId: 'steps', durationMs: 2600 },
      { id: 'rf-b08', sceneId: 'rf-04-recap', action: 'wait', targetId: 'student-restate', durationMs: 2200 },
    ],
    qualityStatus: 'passed',
  },
]

export type GoldenMainlineCourseId = (typeof GOLDEN_MAINLINE_COURSES)[number]['id']

export function getGoldenMainlineCourse(courseId: string): MainlineCourse | undefined {
  return GOLDEN_MAINLINE_COURSES.find(course => course.id === courseId)
}
